# Generated by Django 5.2.7 on 2025-10-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Study', 'Study'), ('Shopping', 'Shopping'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AddField(
            model_name='todo',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('1', '①'), ('2', '②'), ('3', '③'), ('4', '④'), ('5', '⑤'), ('6', '⑥'), ('7', '⑦'), ('8', '⑧'), ('9', '⑨'), ('10', '⑩')], default='5', max_length=2),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETED'), ('P', 'PENDING')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
